// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBiwJOsbjfQDx0ADMhuIY5MMwQBBZaoOQ',
    appId: '1:193445089560:web:474be18b7c2dc632c30e6d',
    messagingSenderId: '193445089560',
    projectId: 'kolachidailybook',
    authDomain: 'kolachidailybook.firebaseapp.com',
    storageBucket: 'kolachidailybook.appspot.com',
    measurementId: 'G-0EVRMS2YSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmS1WXO6Fcb0PXq7Ez8fCw-JTTT9tUsDk',
    appId: '1:193445089560:android:d28432c7518f9a94c30e6d',
    messagingSenderId: '193445089560',
    projectId: 'kolachidailybook',
    storageBucket: 'kolachidailybook.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzWRj-qAtR9BtUO8_JCCqmlOYPiSmLUMs',
    appId: '1:193445089560:ios:068320739e00a25ac30e6d',
    messagingSenderId: '193445089560',
    projectId: 'kolachidailybook',
    storageBucket: 'kolachidailybook.appspot.com',
    iosBundleId: 'com.example.kolachibook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzWRj-qAtR9BtUO8_JCCqmlOYPiSmLUMs',
    appId: '1:193445089560:ios:43a58279fd193d38c30e6d',
    messagingSenderId: '193445089560',
    projectId: 'kolachidailybook',
    storageBucket: 'kolachidailybook.appspot.com',
    iosBundleId: 'com.example.kolachibook.RunnerTests',
  );
}
